---
title: Tweedimensionale lijsten in Python
hero_image: images/banner.png
description: 2D-lijsten maken en openen in Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - title: 2D-lijsten in Python
