---
title: Listas bidimensionales en Python
hero_image: images/banner.png
description: Creando y accediendo listas 2D en Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: ""
steps:
  - title: Listas 2D en Python
